### ISSUE TITLE
Exception is thrown at the end of recording from mic in NodeJS sample code

### ISSUE THREAD

**Issue by awoehler** [googleapis/nodejs-media-translation#106]
An exception is thrown on the last result because the stream has already been destroyed. 

#### Environment details

  - OS: MacOS 10.15.7
  - Node.js version: 10.16.0
  - npm version: 6.14.11
  - `@google-cloud/media-translation` version: 2.2.1

#### Steps to reproduce

  1. Run the NodeJS sample to record from the microphone code after updating the TODO items

**Comment by meredithslota** [comment]
@fhinkel I don't totally understand why this issue is assigned to me - how can I help? :)

**Comment by telpirion** [comment]
Let's close this for now. It looks like @awoehler has submitted a fix.
