### ISSUE TITLE
typo on line 48

### ISSUE THREAD

**Issue by ihsansengun** [googleapis/nodejs-media-translation#136]
https://github.com/googleapis/nodejs-media-translation/blob/cfaeb1ce0699eaa372d1ed726bd445177dafe546/samples/quickstart.js#L48

**Comment by bcoe** [comment]
@ihsansengun the typo isn't jumping out at me, what's wrong with this code?

**Comment by ihsansengun** [comment]
In the comment, there is a little misspelling. // targetLangauge, which isn't a big concern, but it can be confusing when you first time uncomment it and assign a value (BCP-47)

**Comment by munkhuushmgl** [comment]
I do not understand what you are suggesting to change?
Could you share code snippet for this [demonstration purpose]?
