### ISSUE TITLE
Error: 3 INVALID_ARGUMENT: Invalid BCP-47 language code: tu-TU

### ISSUE THREAD

**Issue by ihsansengun** [googleapis/nodejs-media-translation#137]
https://github.com/googleapis/nodejs-media-translation/blob/cfaeb1ce0699eaa372d1ed726bd445177dafe546/samples/translate_from_mic.js#L78

Wrong BCP-47 code for Turkish. It should be replaced with tr-TR.

**Comment by bcoe** [comment]
@ihsansengun where is is the incorrect language code being used?

**Comment by ihsansengun** [comment]
According to the documentation, Turkish's BCP-47 code is tu-TU. When I assign tu-Tu to targetLanguage I get an error.
https://cloud.google.com/translate/media/docs/languages

**Comment by orionnye** [comment]
Hey @ihsansengun! Thanks for bringing this to our attention, we'll be getting in contact with the documentation team to fix this issue.

**Comment by kweinmeister** [comment]
The code has been updated in the [documentation](https://cloud.google.com/translate/media/docs/languages): 

Language | BCP-47 code
-- | --
Turkish | tr-TR
